#!/bin/sh
# Gluetun port-forwarding host-side poller.
#
# Run from cron every minute on the Pi (NOT inside any container). Reads the
# PIA-assigned forwarded port from gluetun's bind-mounted state file and pushes
# it into Deluge's live config via deluge-console — no Deluge restart needed.
#
# Why a poller instead of gluetun's VPN_PORT_FORWARDING_UP_COMMAND hook:
# gluetun's Alpine container has neither bash nor the docker CLI, so the
# in-container hook can't reach the deluge container. Research R3 documented
# this poller as the explicit fallback.
#
# Cadence trade-off: PIA rotates the port every ~60 days. A 60-second polling
# lag at rotation time is irrelevant.
#
# Idempotent — exits 0 with no change if the port has not moved since last run.
#
# IMPORTANT: do NOT edit this file via `echo` or heredoc. The 014 incident
# (vpn-up.sh broken for 7 weeks by a literal backslash in the shebang) was
# caused by exactly that. Use a real editor.

set -eu

PORT_JSON=/home/john/docker/gluetun/piaportforward.json
STATE_FILE=/home/john/docker/.last-forwarded-port
LOG_FILE=/home/john/docker/gluetun-port-hook.log

log() {
    echo "$(date -Is) $*" >> "${LOG_FILE}"
}

if [ ! -f "${PORT_JSON}" ]; then
    # Gluetun hasn't written the file yet (still establishing tunnel); silent exit
    exit 0
fi

# Extract port without jq dependency
NEW_PORT=$(sed -n 's/.*"port":\([0-9]*\).*/\1/p' "${PORT_JSON}")

if [ -z "${NEW_PORT}" ]; then
    log "ERROR: could not parse port from ${PORT_JSON}"
    exit 1
fi

case "${NEW_PORT}" in
    ''|*[!0-9]*)
        log "ERROR: invalid port '${NEW_PORT}' (not numeric)"
        exit 1
        ;;
esac

if [ "${NEW_PORT}" -lt 1024 ] || [ "${NEW_PORT}" -gt 65535 ]; then
    log "ERROR: invalid port '${NEW_PORT}' (must be 1024-65535)"
    exit 1
fi

OLD_PORT=$(cat "${STATE_FILE}" 2>/dev/null || echo "")

if [ "${NEW_PORT}" = "${OLD_PORT}" ]; then
    # No change — fast no-op
    exit 0
fi

log "port change: ${OLD_PORT:-<none>} -> ${NEW_PORT}"

if ! docker exec deluge deluge-console -c /config "config --set listen_ports (${NEW_PORT},${NEW_PORT})" >> "${LOG_FILE}" 2>&1; then
    log "ERROR: deluge-console listen_ports update failed"
    exit 1
fi

if ! docker exec deluge deluge-console -c /config "config --set random_port False" >> "${LOG_FILE}" 2>&1; then
    log "ERROR: deluge-console random_port update failed"
    exit 1
fi

echo "${NEW_PORT}" > "${STATE_FILE}"
log "OK: deluge listen_ports = (${NEW_PORT}, ${NEW_PORT})"
