#!/bin/sh
# Gluetun → Deluge host-side sync poller.
#
# Run from cron every minute on the Pi (NOT inside any container). Keeps two
# Deluge settings in sync with gluetun's current state:
#
#   1. listen_ports  ← PIA-assigned forwarded port (/home/john/docker/gluetun/piaportforward.json)
#   2. listen_interface  ← current tun0 IP inside the gluetun netns
#
# Both are pushed into Deluge's live config via deluge-console — no restart needed.
#
# Why listen_interface needs tracking: libtorrent's expand_unspecified_address()
# deliberately skips POINTOPOINT interfaces (tun0) when listen_interface is empty
# or "0.0.0.0". Without an explicit tun0 IP in listen_interface, Deluge binds only
# to the docker bridge interface and peers arriving via the VPN's forwarded port
# find nothing listening. The tun0 IP changes on every VPN reconnect.
#
# Why a poller instead of gluetun's VPN_PORT_FORWARDING_UP_COMMAND hook:
# gluetun's Alpine container has neither bash nor the docker CLI, so the
# in-container hook can't reach the deluge container. Research R3 documented
# this poller as the explicit fallback.
#
# Cadence trade-off: PIA rotates the port every ~60 days and tun0 IP changes on
# each tunnel reconnect (minutes, not seconds). A 60-second polling lag is fine.
#
# Idempotent — both sync blocks exit early if state is unchanged.
#
# IMPORTANT: do NOT edit this file via `echo` or heredoc. The 014 incident
# (vpn-up.sh broken for 7 weeks by a literal backslash in the shebang) was
# caused by exactly that. Use a real editor.

set -eu

PORT_JSON=/home/john/docker/gluetun/piaportforward.json
PORT_STATE_FILE=/home/john/docker/.last-forwarded-port
TUN_IP_STATE_FILE=/home/john/docker/.last-tun0-ip
LOG_FILE=/home/john/docker/gluetun-port-hook.log

log() {
    echo "$(date -Is) $*" >> "${LOG_FILE}"
}

# ----------------------------------------------------------------------------
# 1. Sync listen_ports with PIA forwarded port
# ----------------------------------------------------------------------------

sync_port() {
    if [ ! -f "${PORT_JSON}" ]; then
        # Gluetun hasn't written the file yet (still establishing tunnel); skip
        return 0
    fi

    NEW_PORT=$(sed -n 's/.*"port":\([0-9]*\).*/\1/p' "${PORT_JSON}")

    if [ -z "${NEW_PORT}" ]; then
        log "ERROR: could not parse port from ${PORT_JSON}"
        return 1
    fi

    case "${NEW_PORT}" in
        ''|*[!0-9]*)
            log "ERROR: invalid port '${NEW_PORT}' (not numeric)"
            return 1
            ;;
    esac

    if [ "${NEW_PORT}" -lt 1024 ] || [ "${NEW_PORT}" -gt 65535 ]; then
        log "ERROR: invalid port '${NEW_PORT}' (must be 1024-65535)"
        return 1
    fi

    OLD_PORT=$(cat "${PORT_STATE_FILE}" 2>/dev/null || echo "")
    if [ "${NEW_PORT}" = "${OLD_PORT}" ]; then
        return 0
    fi

    log "port change: ${OLD_PORT:-<none>} -> ${NEW_PORT}"

    if ! docker exec deluge deluge-console -c /config "config --set listen_ports (${NEW_PORT},${NEW_PORT})" >> "${LOG_FILE}" 2>&1; then
        log "ERROR: deluge-console listen_ports update failed"
        return 1
    fi

    if ! docker exec deluge deluge-console -c /config "config --set random_port False" >> "${LOG_FILE}" 2>&1; then
        log "ERROR: deluge-console random_port update failed"
        return 1
    fi

    echo "${NEW_PORT}" > "${PORT_STATE_FILE}"
    log "OK: deluge listen_ports = (${NEW_PORT}, ${NEW_PORT})"
}

# ----------------------------------------------------------------------------
# 2. Sync listen_interface with current tun0 IP
# ----------------------------------------------------------------------------

sync_tun_ip() {
    # Read tun0 IP from inside the gluetun netns. If gluetun is down or tun0
    # doesn't exist, skip quietly — the VPN is being re-established and the
    # watchdog will catch up on the next cycle.
    NEW_IP=$(docker exec gluetun ip -4 addr show tun0 2>/dev/null \
        | awk '/inet / {print $2}' | cut -d/ -f1 || true)

    if [ -z "${NEW_IP}" ]; then
        return 0
    fi

    # Basic IPv4 shape check
    case "${NEW_IP}" in
        *.*.*.*) ;;
        *)
            log "ERROR: tun0 IP '${NEW_IP}' is not a valid IPv4 address"
            return 1
            ;;
    esac

    OLD_IP=$(cat "${TUN_IP_STATE_FILE}" 2>/dev/null || echo "")
    if [ "${NEW_IP}" = "${OLD_IP}" ]; then
        return 0
    fi

    log "tun0 IP change: ${OLD_IP:-<none>} -> ${NEW_IP}"

    if ! docker exec deluge deluge-console -c /config "config --set listen_interface ${NEW_IP}" >> "${LOG_FILE}" 2>&1; then
        log "ERROR: deluge-console listen_interface update failed"
        return 1
    fi

    echo "${NEW_IP}" > "${TUN_IP_STATE_FILE}"
    log "OK: deluge listen_interface = ${NEW_IP}"
}

# ----------------------------------------------------------------------------
# main: run both sync blocks; don't let one failing block the other.
# ----------------------------------------------------------------------------

PORT_RC=0
TUN_RC=0
sync_port || PORT_RC=$?
sync_tun_ip || TUN_RC=$?

if [ "${PORT_RC}" -ne 0 ] || [ "${TUN_RC}" -ne 0 ]; then
    exit 1
fi
exit 0
