apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://host.docker.internal:8086
    database: network_metrics
    user: grafana
    secureJsonData:
      password: grafanapass
    isDefault: true
    editable: false
